//
// Generated file, do not edit! Created by opp_msgtool 6.2 from TrustSMTP.msg.
//

#ifndef __PEYAL_TRUSTSMTP_M_H
#define __PEYAL_TRUSTSMTP_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0602
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace peyal {

class TrustSMTPMessage;
class SMTPCommand;
class SMTPResponse;
class SMTPData;
class TrustQueryMsg;
class TrustReplyMsg;

}  // namespace peyal

// cplusplus {{
#include <string>
// }}


namespace peyal {

/**
 * Class generated from <tt>TrustSMTP.msg:9</tt> by opp_msgtool.
 * <pre>
 * message TrustSMTPMessage
 * {
 *     string from;
 *     string to;
 *     int msgId;
 *     int sizeBytes;
 *     double trustScore;
 *     bool isHandshake = false;
 *     bool isData = false;
 * }
 * </pre>
 */
class TrustSMTPMessage : public ::omnetpp::cMessage
{
  protected:
    ::omnetpp::opp_string from;
    ::omnetpp::opp_string to;
    int msgId = 0;
    int sizeBytes = 0;
    double trustScore = 0;
    bool isHandshake_ = false;
    bool isData_ = false;

  private:
    void copy(const TrustSMTPMessage& other);

  protected:
    bool operator==(const TrustSMTPMessage&) = delete;

  public:
    TrustSMTPMessage(const char *name=nullptr, short kind=0);
    TrustSMTPMessage(const TrustSMTPMessage& other);
    virtual ~TrustSMTPMessage();
    TrustSMTPMessage& operator=(const TrustSMTPMessage& other);
    virtual TrustSMTPMessage *dup() const override {return new TrustSMTPMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getFrom() const;
    virtual void setFrom(const char * from);

    virtual const char * getTo() const;
    virtual void setTo(const char * to);

    virtual int getMsgId() const;
    virtual void setMsgId(int msgId);

    virtual int getSizeBytes() const;
    virtual void setSizeBytes(int sizeBytes);

    virtual double getTrustScore() const;
    virtual void setTrustScore(double trustScore);

    virtual bool isHandshake() const;
    virtual void setIsHandshake(bool isHandshake);

    virtual bool isData() const;
    virtual void setIsData(bool isData);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TrustSMTPMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TrustSMTPMessage& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>TrustSMTP.msg:21</tt> by opp_msgtool.
 * <pre>
 * message SMTPCommand
 * {
 *     string command;
 *     string parameter;
 *     string clientId;
 *     double trustScore;
 * }
 * </pre>
 */
class SMTPCommand : public ::omnetpp::cMessage
{
  protected:
    ::omnetpp::opp_string command;
    ::omnetpp::opp_string parameter;
    ::omnetpp::opp_string clientId;
    double trustScore = 0;

  private:
    void copy(const SMTPCommand& other);

  protected:
    bool operator==(const SMTPCommand&) = delete;

  public:
    SMTPCommand(const char *name=nullptr, short kind=0);
    SMTPCommand(const SMTPCommand& other);
    virtual ~SMTPCommand();
    SMTPCommand& operator=(const SMTPCommand& other);
    virtual SMTPCommand *dup() const override {return new SMTPCommand(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getCommand() const;
    virtual void setCommand(const char * command);

    virtual const char * getParameter() const;
    virtual void setParameter(const char * parameter);

    virtual const char * getClientId() const;
    virtual void setClientId(const char * clientId);

    virtual double getTrustScore() const;
    virtual void setTrustScore(double trustScore);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SMTPCommand& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SMTPCommand& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>TrustSMTP.msg:29</tt> by opp_msgtool.
 * <pre>
 * message SMTPResponse
 * {
 *     int code;
 *     string statusText;
 *     bool success;
 * }
 * </pre>
 */
class SMTPResponse : public ::omnetpp::cMessage
{
  protected:
    int code = 0;
    ::omnetpp::opp_string statusText;
    bool success = false;

  private:
    void copy(const SMTPResponse& other);

  protected:
    bool operator==(const SMTPResponse&) = delete;

  public:
    SMTPResponse(const char *name=nullptr, short kind=0);
    SMTPResponse(const SMTPResponse& other);
    virtual ~SMTPResponse();
    SMTPResponse& operator=(const SMTPResponse& other);
    virtual SMTPResponse *dup() const override {return new SMTPResponse(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getCode() const;
    virtual void setCode(int code);

    virtual const char * getStatusText() const;
    virtual void setStatusText(const char * statusText);

    virtual bool getSuccess() const;
    virtual void setSuccess(bool success);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SMTPResponse& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SMTPResponse& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>TrustSMTP.msg:36</tt> by opp_msgtool.
 * <pre>
 * message SMTPData
 * {
 *     string from;
 *     string to;
 *     string subject;
 *     string body;
 *     int sizeBytes;
 *     double trustScore;
 *     int msgId;
 * }
 * </pre>
 */
class SMTPData : public ::omnetpp::cMessage
{
  protected:
    ::omnetpp::opp_string from;
    ::omnetpp::opp_string to;
    ::omnetpp::opp_string subject;
    ::omnetpp::opp_string body;
    int sizeBytes = 0;
    double trustScore = 0;
    int msgId = 0;

  private:
    void copy(const SMTPData& other);

  protected:
    bool operator==(const SMTPData&) = delete;

  public:
    SMTPData(const char *name=nullptr, short kind=0);
    SMTPData(const SMTPData& other);
    virtual ~SMTPData();
    SMTPData& operator=(const SMTPData& other);
    virtual SMTPData *dup() const override {return new SMTPData(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getFrom() const;
    virtual void setFrom(const char * from);

    virtual const char * getTo() const;
    virtual void setTo(const char * to);

    virtual const char * getSubject() const;
    virtual void setSubject(const char * subject);

    virtual const char * getBody() const;
    virtual void setBody(const char * body);

    virtual int getSizeBytes() const;
    virtual void setSizeBytes(int sizeBytes);

    virtual double getTrustScore() const;
    virtual void setTrustScore(double trustScore);

    virtual int getMsgId() const;
    virtual void setMsgId(int msgId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SMTPData& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SMTPData& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>TrustSMTP.msg:48</tt> by opp_msgtool.
 * <pre>
 * message TrustQueryMsg
 * {
 *     string sender;
 * }
 * </pre>
 */
class TrustQueryMsg : public ::omnetpp::cMessage
{
  protected:
    ::omnetpp::opp_string sender;

  private:
    void copy(const TrustQueryMsg& other);

  protected:
    bool operator==(const TrustQueryMsg&) = delete;

  public:
    TrustQueryMsg(const char *name=nullptr, short kind=0);
    TrustQueryMsg(const TrustQueryMsg& other);
    virtual ~TrustQueryMsg();
    TrustQueryMsg& operator=(const TrustQueryMsg& other);
    virtual TrustQueryMsg *dup() const override {return new TrustQueryMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getSender() const;
    virtual void setSender(const char * sender);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TrustQueryMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TrustQueryMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>TrustSMTP.msg:53</tt> by opp_msgtool.
 * <pre>
 * message TrustReplyMsg
 * {
 *     string sender;
 *     double score;
 * }
 * </pre>
 */
class TrustReplyMsg : public ::omnetpp::cMessage
{
  protected:
    ::omnetpp::opp_string sender;
    double score = 0;

  private:
    void copy(const TrustReplyMsg& other);

  protected:
    bool operator==(const TrustReplyMsg&) = delete;

  public:
    TrustReplyMsg(const char *name=nullptr, short kind=0);
    TrustReplyMsg(const TrustReplyMsg& other);
    virtual ~TrustReplyMsg();
    TrustReplyMsg& operator=(const TrustReplyMsg& other);
    virtual TrustReplyMsg *dup() const override {return new TrustReplyMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getSender() const;
    virtual void setSender(const char * sender);

    virtual double getScore() const;
    virtual void setScore(double score);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TrustReplyMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TrustReplyMsg& obj) {obj.parsimUnpack(b);}


}  // namespace peyal


namespace omnetpp {

template<> inline peyal::TrustSMTPMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<peyal::TrustSMTPMessage*>(ptr.get<cObject>()); }
template<> inline peyal::SMTPCommand *fromAnyPtr(any_ptr ptr) { return check_and_cast<peyal::SMTPCommand*>(ptr.get<cObject>()); }
template<> inline peyal::SMTPResponse *fromAnyPtr(any_ptr ptr) { return check_and_cast<peyal::SMTPResponse*>(ptr.get<cObject>()); }
template<> inline peyal::SMTPData *fromAnyPtr(any_ptr ptr) { return check_and_cast<peyal::SMTPData*>(ptr.get<cObject>()); }
template<> inline peyal::TrustQueryMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<peyal::TrustQueryMsg*>(ptr.get<cObject>()); }
template<> inline peyal::TrustReplyMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<peyal::TrustReplyMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __PEYAL_TRUSTSMTP_M_H

